services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-personal-ai-local

  redis:
    image: redis:7.4.4-alpine3.21
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data
    networks:
      - my-personal-ai-local

  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # HTTP
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://qdrant:6333/collections"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - my-personal-ai-local

networks:
  my-personal-ai-local:
    external: true

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
